
## activate python environment


## run model
python seqmodel/run.py --init_version=0.0.0 --init_task=ptmask --lr=0.0001 --activate_env_command='' --deactivate_env_command='' --job_author=test-script --gpus=0 --limit_val_batches=10.0 --deterministic=True --check_val_every_n_epoch=10 --default_root_dir=out/v=0.0.0_t=ptmask_/default_data/default_model/lr=1.00E-04/19

## deactivate python environment


# Job script auto-generated by test-script using ShellJob v0.0.0 on 2021-06-12 16:23:27.033769.
